
polar:
  greeting: Welcome to polar bookshop
server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polar_catalog_db?user=user&password=Password
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 10
  application:
    name: Catalog
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        multiplier: 1.1
        initial-interval: 1000
        max-interval: 2000
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        exclude: refresh
